version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      # Gắn thư mục chroma_db ở máy thật vào /app/chroma_db trong container
      - ./chroma_db:/app/chroma_db 
    networks:
      - emi_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  emi_network:
    driver: bridge